DROP FUNCTION IF EXISTS `CALCULATE_TOTAL_CHARGES`;
DELIMITER //

CREATE FUNCTION CALCULATE_TOTAL_CHARGES(
    tds DOUBLE,
    chargesGST DOUBLE,
    pgCharge DOUBLE
    
)
RETURNS DOUBLE 
READS SQL DATA

BEGIN
	RETURN ROUND(tds+chargesGST+pgCharge,2);
END //

DELIMITER ;
