spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: jdbc:mysql://localhost:3306/reconcii
    username: reconcii-application-client
    password: reconcii8a780c6d
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 300000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
#      ddl-auto: create
      ddl-auto: none
#      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        #use_sql_comments: true
        format_sql: true
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      username: mcd-application-client
#      password: 3307324b05f5
#      database: mcd
#      authentication-database: admin
s3:
  bucket: corepeelers
cpl:
  s3:
    client:
      required: false
logging:
  level:
    root: INFO
    com:
      cpl: INFO
sftp:
  root: C:\sftp
  dotpay:
    API_KEY: fdc01a72-5043-4d6a-b7b7-0b5d92138f81
    API_SECRET: 9vfo3eRNIcY7Vc2F9zyQEU3raXT5GCv92f6xOr-6Vkk

manualUpload:
  email: prateet.garg@corepeelers.com
  header: Local
temp:
  mprpath: D:\tmp\mpr
