spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: jdbc:mysql://coreco-mysql.cpzxmgfkrh6g.ap-south-1.rds.amazonaws.com:3306/poc_reconcii
    username: admin
    password: One4the$#
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 300000
      maximum-pool-size: 40
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        #use_sql_comments: true
        format_sql: true
#  data:
#    mongodb:
#      host: 172.31.13.243
#      port: 27017
#      username: mcd-application-client
#      password: 3307324b05f5
#      database: mcd
#      authentication-database: mcd
cpl:
  s3:
    client:
      required: false
logging:
  level:
    root: INFO
    com:
      cpl: INFO
sftp:
  root: /var/sftp
  dotpay:
    API_KEY: fdc01a72-5043-4d6a-b7b7-0b5d92138f81
    API_SECRET: 9vfo3eRNIcY7Vc2F9zyQEU3raXT5GCv92f6xOr-6Vkk


manualUpload:
  email: prateet.garg@corepeelers.com
  header: Stage
  
scheduled:
  pool:
    size: 5
temp:
  mprpath: /root/tmp/mpr