INSERT INTO mcd.customised_report_filters (name, technical_name, sql_field, category) VALUES
('City', 'city', 'city', 'Magicpin'),
('Commission', 'commission', 'commission', 'Magicpin'),
('Date', 'date', 'date', 'Magicpin'),
('Debited Amount', 'debitedAmount', 'debited_amount', 'Magicpin'),
('GST', 'gst', 'gst', 'Magicpin'),
('GST on Commission', 'gstOnCommission', 'gst_on_commission', 'Magicpin'),
('Item Amount', 'itemAmount', 'item_amount', 'Magicpin'),
('Locality', 'locality', 'locality', 'Magicpin'),
('Merchant GMV', 'merchantGMV', 'merchant_gmv', 'Magicpin'),
('Merchant Name', 'merchantName', 'merchant_name', 'Magicpin'),
('MFP', 'mfp', 'mfp', 'Magicpin'),
('MID', 'mid', 'mid', 'Magicpin'),
('Net Payable', 'netPayable', 'net_payable', 'Magicpin'),
('Order ID', 'orderId', 'order_id', 'Magicpin'),
('Order Status', 'orderStatus', 'order_status', 'Magicpin'),
('Packaging Charge', 'packagingCharge', 'packaging_charge', 'Magicpin'),
('PID', 'pid', 'pid', 'Magicpin'),
('Reconciled', 'reconciled', 'reconciled', 'Magicpin'),
('Rejection ID', 'rejectionId', 'rejection_id', 'Magicpin'),
('Rejection Reason', 'rejectionReason', 'rejection_reason', 'Magicpin'),
('TDS', 'tds', 'tds', 'Magicpin');
