INSERT INTO mcd.customised_report_filters (name, technical_name, sql_field, category) VALUES
('Delivery Fee', 'deliveryFee', 'delivery_fee', 'Swiggy'),
('Merchant Cancellation Charges', 'merchantCancellationCharges', 'merchant_cancellation_charges', 'Swiggy'),
('Merchant Discount', 'merchantDiscount', 'merchant_discount', 'Swiggy'),
('Access Fee', 'accessFee', 'access_fee', 'Swiggy'),
('Area', 'area', 'area', 'Swiggy'),
('Base Order ID', 'baseOrderId', 'base_order_id', 'Swiggy'),
('Buyer Cancellation Cost Sharing', 'buyerCancellationCostSharing', 'buyer_cancellation_cost_sharing', 'Swiggy'),
('Call Center Service Fees', 'callCenterServiceFees', 'call_center_servicefees', 'Swiggy'),
('Cancellation Attribution', 'cancellationAttribution', 'cancellation_attribution', 'Swiggy'),
('Cancellation Policy Applied', 'cancellationPolicyApplied', 'cancellation_policy_applied', 'Swiggy'),
('Cancellation Time', 'cancellationTime', 'cancellation_time', 'Swiggy'),
('Cash Pre Payment at Restaurant', 'cashPrePaymentAtRestaurant', 'cash_pre_payment_at_restaurant', 'Swiggy'),
('City', 'city', 'city', 'Swiggy'),
('Collection Fee', 'collectionFee', 'collection_fee', 'Swiggy'),
('Coupon Code Applied', 'couponCodeApplied', 'coupon_code_applied', 'Swiggy'),
('Customer Payable', 'customerPayable', 'customer_payable', 'Swiggy'),
('Discount Campaign ID', 'discountCampaignId', 'discount_campaign_id', 'Swiggy'),
('Discount on Long Distance Fee', 'discountOnLongDistanceFee', 'discount_on_long_distance_fee', 'Swiggy'),
('Discount on Swiggy Platform Service Fee', 'discountOnSwiggyPlatformServiceFee', 'discount_on_swiggy_platform_service_fee', 'Swiggy'),
('Disputed Order Remarks', 'disputedOrderRemarks', 'disputed_order_remarks', 'Swiggy'),
('GST Deduction', 'gstDeduction', 'gst_deduction', 'Swiggy'),
('GST on Order (Including Cess)', 'gstOnOrderIncludingCess', 'gst_on_order_including_cess', 'Swiggy'),
('Is Replicated', 'isReplicated', 'is_replicated', 'Swiggy'),
('Item Total', 'itemTotal', 'item_total', 'Swiggy'),
('Last Mile Distance', 'lastMileDistance', 'last_mile_distance', 'Swiggy'),
('Long Distance Applicable on Order', 'longDistanceApplicableOnOrder', 'long_distance_applicable_on_order', 'Swiggy'),
('Long Distance Fee', 'longDistanceFee', 'long_distance_fee', 'Swiggy'),
('MFR Pressed', 'mfrPressed', 'mfr_pressed', 'Swiggy'),
('MRP Items', 'mrpItems', 'mrp_items', 'Swiggy'),
('Net Bill Value (Without Tax)', 'netBillValueWithoutTax', 'net_bill_value_without_tax', 'Swiggy'),
('Net Payable Amount (After TCS and TDS)', 'netPayableAmountAfterTCSAndTDS', 'net_payable_amount_after_tcs_and_tds', 'Swiggy'),
('Net Payable Amount (Before TCS and TDS)', 'netPayableAmountBeforeTCSAndTDS', 'net_payable_amount_before_tcs_and_tds', 'Swiggy'),
('Order Date', 'orderDate', 'order_date', 'Swiggy'),
('Order No', 'orderNo', 'order_no', 'Swiggy'),
('Order Payment Type', 'orderPaymentType', 'order_payment_type', 'Swiggy'),
('Order Status', 'orderStatus', 'order_status', 'Swiggy'),
('Packing and Service Charges', 'packingAndServiceCharges', 'packing_and_service_charges', 'Swiggy'),
('Pick Up Status', 'pickUpStatus', 'pick_up_status', 'Swiggy'),
('Reconciled', 'reconciled', 'reconciled', 'Swiggy'),
('Refund for Disputed Order', 'refundForDisputedOrder', 'refund_for_disputed_order', 'Swiggy'),
('Restaurant ID', 'restaurantId', 'restaurant_id', 'Swiggy'),
('Restaurant Name', 'restaurantName', 'restaurant_name', 'Swiggy'),
('Swiggy Platform Fee Chargeable On', 'swiggyPlatformFeeChargeableOn', 'swiggy_platform_fee_chargeable_on', 'Swiggy'),
('Swiggy Platform Service Fee', 'swiggyPlatformServiceFee', 'swiggy_platform_service_fee', 'Swiggy'),
('Swiggy Platform Service Fee Percent', 'swiggyPlatformServiceFeePercent', 'swiggy_platform_servicefee_percent', 'Swiggy'),
('TCS', 'tcs', 'tcs', 'Swiggy'),
('TDS', 'tds', 'tds', 'Swiggy'),
('Total GST', 'totalGST', 'total_gst', 'Swiggy'),
('Total of Order Level Adjustments', 'totalOfOrderLevelAdjustments', 'total_of_order_level_adjustments', 'Swiggy'),
('Total Swiggy Fee', 'totalSwiggyFee', 'total_swiggy_fee', 'Swiggy'),
('Total Swiggy Service Fee', 'totalSwiggyServiceFee', 'total_swiggy_service_fee', 'Swiggy');
