INSERT INTO mcd.customised_report_filters (name, technical_name, sql_field, category) VALUES
('Action', 'action', 'action', 'Zomato'),
('Actual Discount', 'actualDiscount', 'actual_discount', 'Zomato'),
('Bill Subtotal', 'billSubtotal', 'bill_subtotal', 'Zomato'),
('Cancellation Refund', 'cancellationRefund', 'cancellation_refund', 'Zomato'),
('City', 'city', 'city', 'Zomato'),
('City ID', 'cityId', 'city_id', 'Zomato'),
('Commission Rate', 'commissionRate', 'commission_rate', 'Zomato'),
('Commission Value', 'commissionValue', 'commission_value', 'Zomato'),
('Credit Note Amount', 'creditNoteAmount', 'credit_note_amount', 'Zomato'),
('Currency', 'currency', 'currency', 'Zomato'),
('Customer Compensation', 'customerCompensation', 'customer_compensation', 'Zomato'),
('Customer Discount', 'customerDiscount', 'customer_discount', 'Zomato'),
('Date Range', 'dateRange', 'date_range', 'Zomato'),
('End Order Date', 'endOrderDate', 'end_order_date', 'Zomato'),
('Final Amount', 'finalAmount', 'final_amount', 'Zomato'),
('Gst Customer Bill', 'gstCustomerBill', 'gst_customer_bill', 'Zomato'),
('Icecream Deductions', 'icecreamDeductions', 'icecream_deductions', 'Zomato'),
('Icecream Handling', 'icecreamHandling', 'icecream_handling', 'Zomato'),
('Logistics Charge', 'logisticsCharge', 'logistics_charge', 'Zomato'),
('Merchant Delivery Charge', 'merchantDeliveryCharge', 'merchant_delivery_charge', 'Zomato'),
('Merchant Pack Charge', 'merchantPackCharge', 'merchant_pack_charge', 'Zomato'),
('Merchant Voucher Discount', 'merchantVoucherDiscount', 'merchant_voucher_discount', 'Zomato'),
('MID', 'mid', 'mid', 'Zomato'),
('Net Amount', 'netAmount', 'net_amount', 'Zomato'),
('Order Support Cost', 'orderSupportCost', 'oder_support_cost', 'Zomato'),
('Order Date', 'orderDate', 'order_date', 'Zomato'),
('Order ID', 'orderId', 'order_id', 'Zomato'),
('Order Invoice Number', 'orderInvNo', 'order_inv_no', 'Zomato'),
('Payment Method', 'paymentMethod', 'payment_method', 'Zomato'),
('PG Charge', 'pgCharge', 'pg_charge', 'Zomato'),
('PG Charge Base', 'pgChargeBase', 'pg_charge_base', 'Zomato'),
('Pro Discount Passthrough', 'proDiscountPassthrough', 'pro_discount_passthrough', 'Zomato'),
('Promo Code', 'promoCode', 'promo_code', 'Zomato'),
('Promo Recovery Adjustment', 'promoRecoveryAdj', 'promo_recovery_adj', 'Zomato'),
('Rejection Penalty Charge', 'rejectionPenaltyCharge', 'rejection_penalty_charge', 'Zomato'),
('Restaurant ID', 'resId', 'res_id', 'Zomato'),
('Service ID', 'serviceId', 'service_id', 'Zomato'),
('Source Tax', 'sourceTax', 'source_tax', 'Zomato'),
('Source Tax Base', 'sourceTaxBase', 'source_tax_base', 'Zomato'),
('Start Order Date', 'startOrderDate', 'start_order_date', 'Zomato'),
('Status', 'status', 'status', 'Zomato'),
('Tax Rate', 'taxRate', 'tax_rate', 'Zomato'),
('Taxes Zomato Fee', 'taxesZomatoFee', 'taxes_zomato_fee', 'Zomato'),
('TCS Amount', 'tcsAmount', 'tcs_amount', 'Zomato'),
('TCS Base', 'tcsBase', 'tcs_base', 'Zomato'),
('TDS Amount', 'tdsAmount', 'tds_amount', 'Zomato'),
('Total Amount', 'totalAmount', 'total_amount', 'Zomato'),
('User Credit Charge', 'userCreditCharge', 'user_credit_charge', 'Zomato'),
('UTR Date', 'utrDate', 'utr_date', 'Zomato'),
('UTR Number', 'utrNumber', 'utr_number', 'Zomato'),
('Zomato Voucher Discount', 'zomatoVoucherDiscount', 'zomato_voucher_discount', 'Zomato'),
('Restaurant Name', 'resName', 'res_name', 'Zomato'),
('Business ID', 'businessId', 'business_id', 'Zomato'),
('Reconciled', 'reconciled', 'reconciled', 'Zomato');

